/**
 * AsciiStatic — the honest, zero-JavaScript frame of the site's signature art.
 *
 * Spec of record: .agents/skills/hokuten-design-director/references/05-motion.md
 * ("ASCII hero" → "static `<img>` fallback (same frame) via `<noscript>` and for
 * reduced-motion/touch/small viewports").
 * Contract of record: site/lib/ascii-types.ts.
 *
 * This is a Server Component: it ships no JavaScript at all. It is BOTH
 *   1. the standalone mobile / reduced-motion / data-saver / JS-off frame, and
 *   2. the layer that `AsciiCanvas` renders underneath itself, so the art is
 *      painted on the very first HTML byte and the canvas is pure progressive
 *      enhancement (see the header of AsciiCanvas.tsx).
 *
 * WHY A PLAIN <img> AND NOT next/image
 * ------------------------------------
 * The asset is an SVG generated by `scripts/ascii-gen.ts`. next/image cannot
 * optimise SVG (it passes it through with `unoptimized`), and its lazy/blur
 * machinery is actively wrong for a hero LCP element. A plain `<img>` with
 * explicit intrinsic dimensions gives the identical CLS guarantee with no
 * client runtime. Dimensions below are the real `viewBox` of both emitted
 * files, not a guess.
 *
 * COLOUR
 * ------
 * An external SVG referenced by `<img src>` is an isolated document, so the
 * host page's `--art-*` custom properties do NOT reach it — the generator's
 * literal fallbacks apply instead. That is correct by construction: the palette
 * is selected per theme (`themePresentation.artPalette`), and each palette's
 * literals are exactly that theme's `--art-*` values from globals.css. Nothing
 * here needs to know which theme is live.
 */

import {
  ASCII_ART_DESCRIPTION,
  ASCII_ASSETS,
  type AsciiPalette,
} from "@/lib/ascii-types";
import { themePresentation } from "@/lib/theme";
import { cn } from "@/lib/utils";

/**
 * Intrinsic box of `public/art/ascii-{gold,blue}.svg` — `viewBox="0 0 960 640"`
 * in BOTH palettes. It is the character grid at the generator's SVG unit scale:
 * `cols * 0.6em = 160 * 6 = 960` by `rows * 1.0em = 64 * 10 = 640`.
 *
 * Exported because `AsciiCanvas` reserves its box from the same numbers — one
 * source of truth for the reserved aspect ratio, so the two components can
 * never disagree and produce a layout shift.
 */
export const ASCII_SVG_BOX = { width: 960, height: 640 } as const;

/** 3 / 2. The ratio any container must reserve to letterbox-free the art. */
export const ASCII_SVG_RATIO = ASCII_SVG_BOX.width / ASCII_SVG_BOX.height;

export type AsciiStaticProps = {
  /** Defaults to the palette this build's theme selected. */
  palette?: AsciiPalette;
  /** Classes for the `<img>` itself. */
  className?: string;
  /**
   * The adjacent visually-hidden description (ACCESSIBILITY LAW: decorative art
   * is `aria-hidden`, but what it depicts may not be invisible to assistive
   * tech). Pass `null` ONLY when a parent already renders one for this same
   * artwork — `AsciiCanvas` does exactly that.
   */
  description?: string | null;
  /**
   * Hero usage: fetch at high priority, since this is the LCP element. Set
   * `false` for any placement below the fold.
   */
  priority?: boolean;
};

export function AsciiStatic({
  palette = themePresentation.artPalette,
  className,
  description = ASCII_ART_DESCRIPTION,
  priority = true,
}: AsciiStaticProps) {
  return (
    <>
      {/* eslint-disable-next-line @next/next/no-img-element -- see header: SVG, unoptimisable, must not lazy-load */}
      <img
        src={ASCII_ASSETS[palette].svg}
        alt=""
        aria-hidden="true"
        width={ASCII_SVG_BOX.width}
        height={ASCII_SVG_BOX.height}
        decoding="async"
        fetchPriority={priority ? "high" : "auto"}
        draggable={false}
        className={cn("block h-auto w-full max-w-full select-none", className)}
      />
      {description === null ? null : (
        <p className="visually-hidden pointer-events-none">{description}</p>
      )}
    </>
  );
}
